
== 待办中心

=== 推送待办任务接口

*基础信息：*

接口地址：/web/todo-task/pushBatch

请求方式：POST （content-type: application/json; charset=utf-8）

接口描述：推送待办任务到待办中心，支持批量，需要确保任务id在同一个服务内唯一

*请求参数：*

____
注意：最外层是appTasks，详见请求示例
____

[cols="<,<,<,<,<",options="header",]
|===
|名称 |类型 |是否必须 |默认值 |备注
|title |string |必须 | |标题 (最长30字符)
|businessType |integer |必须 |0 |业务类型 (0-其他，1-流程，2-任务)
|detailUrl |string |必须 | |移动端详情页面url (最长200字符)
|webDetailUrl |string |非必须 | |PC端详情页面url (最长200字符)
|appTaskId |string |必须 | |任务id (同一个服务内唯一，最长200字符)
|businessStatus |string |非必须 | |业务状态 (最长100字符)
|coverUrl |string |非必须 | |封面图片url (最长200字符)
|customField |KeyValEntry [] |非必须 | |自定义字段
|handleEntry |HandleEntry [] |非必须 | |处理人和处理类型列表
|iconUrl |string |非必须 | |图标url (最长200字符)
|sponsorDepId |integer |非必须 | |发起人部门id
|sponsorId |integer |非必须 | |发起人id
|sponsorTime |string |非必须 | |发起时间 (时间格式：yyyy-MM-dd HH:mm:ss)
|sponsorUnitId |integer |非必须 | |发起人单位id
|summary |string |非必须 | |摘要
|===

customField嵌套结构：

[cols=",,,,",options="header",]
|===
|名称 |类型 |是否必须 |默认值 |备注
|key |string |非必须 | |字段名
|val |string |非必须 | |字段值
|===

handleEntry嵌套结构：

[cols=",,,,",options="header",]
|===
|名称 |类型 |是否必须 |默认值 |备注
|handleType |integer |必须 |1 |处理类型(1-待处理，2-待查阅)
|handlerId |long |必须 | |处理人id
|===

*请求示例：*

[source,json]
----
{
    "appTasks":[
        {
            "businessType":1,
            "detailUrl":"detailUrl",
            "title":"title",
            "appTaskId":"appTaskId",
            "businessStatus":"businessStatus",
            "coverUrl":"coverUrl",
            "customField":[
                {
                    "key":"key",
                    "val":"val"
                }
            ],
            "handleEntry":[
                {
                    "handleType":1,
                    "handlerId":8888890571
                },
                {
                    "handleType":2,
                    "handlerId":8888890572
                }
            ],
            "iconUrl":"iconUrl",
            "sponsorDepId":56169855,
            "sponsorId":8888890573,
            "sponsorTime":"1990-11-30 19:17:55",
            "sponsorUnitId":12624303,
            "summary":"summary"
        }
    ]
}
----

*返回数据：*

[cols="<,<,<,<,<",options="header",]
|===
|名称 |类型 |是否必须 |默认值 |备注
|msg |string |非必须 | |错误说明
|success |boolean |必须 | |请求是否成功 (true-成功，false-失败)
|code |Integer |必须 | |状态码
|===

=== 撤回待办任务接口

*基础信息：*

接口地址：/web/todo-task/revokeBatch

请求方式：POST (content-type: application/json; charset=utf-8)

接口描述：从待办中心移除待办任务，支持批量

*请求参数：*

____
注意：最外层是appTasks，详见请求示例
____

[cols="<,<,<,<,<",options="header",]
|===
|名称 |类型 |是否必须 |默认值 |备注
|appTaskId |string |必须 | |应用中的待办任务id
|handlerIds |integer [] |必须 | |待办任务关联的处理人账号列表
|===

*请求示例：*

[source,json]
----
{
    "appTasks":[
        {
            "appTaskId":"appTaskId",
            "handlerIds":[
                8888890571,
                8888890572,
                8888890573
            ]
        }
    ]
}
----

*返回数据：*

[cols="<,<,<,<,<",options="header",]
|===
|名称 |类型 |是否必须 |默认值 |备注
|msg |string |非必须 | |错误说明
|success |boolean |必须 | |请求是否成功 (true-成功，false-失败)
|code |Integer |必须 | |状态码
|===

=== 结束待办任务接口

*基础信息：*

接口地址：/web/todo-task/finishBatch

请求方式：POST (content-type: application/json; charset=utf-8)

接口描述：将待办任务状态置为”已处理“，支持批量

*请求参数：*

[cols="<,<,<,<,<",options="header",]
|===
|名称 |类型 |是否必须 |默认值 |备注
|appTaskId |string |必须 | |应用中的待办任务id
|handlerIds |integer [] |必须 | |待办任务关联的处理人账号列表
|===

*请求示例：*

[source,json]
----
{
    "appTasks":[
        {
            "appTaskId":"appTaskId",
            "handlerIds":[
                8888890571,
                8888890572,
                8888890573
            ]
        }
    ]
}
----

*返回数据：*

[cols="<,<,<,<,<",options="header",]
|===
|名称 |类型 |是否必须 |默认值 |备注
|msg |string |非必须 | |错误说明
|success |boolean |必须 | |请求是否成功 (true-成功，false-失败)
|code |Integer |必须 | |状态码
|===

=== 发送到指定处理人接口

接口地址：/web/todo-task/sendTaskToHandler

请求方式：POST (content-type: application/json; charset=utf-8)

接口描述：将待办任务推送给指定的处理人，任务必须已存在，不支持批量

*请求参数：*

[cols="<,<,<,<,<",options="header",]
|===
|名称 |类型 |是否必须 |默认值 |备注
|appTaskId |string |必须 | |应用中的待办任务id
|handlerIds |integer [] |必须 | |处理人账号列表
|===

*请求示例：*

[source,json]
----
{
  "appTaskId": "appTaskId",
  "handlerIds": [
    8888890571,
    8888890572,
    8888890573
  ]
}
----

*返回数据：*

[cols="<,<,<,<,<",options="header",]
|===
|名称 |类型 |是否必须 |默认值 |备注
|msg |string |非必须 | |错误说明
|success |boolean |必须 | |请求是否成功 (true-成功，false-失败)
|code |Integer |必须 | |状态码
|===
