== 新闻、公告

=== 新闻、公告推送

接口名称：接收新闻、公告信息 +
接口地址：/news/push +
请求方式：POST（content-type:application/json; charset=utf-8） +
Request请求说明： +

`Body数据格式:` +

[source,json]
....
[{
	"title": "test",
	"publisher": "dsd",
	"digest": "sfdss",
	"fileContent": [{
		"url": "http://ww.baidu.com"
	}],
	"coverImg": "http://baas.uban360.net:21006/sfs/file?digest=fid431e3a147c4291aeae5e19ad82a2994e",
	"categoryId": 184337,
	"baasNewsType": 2,
	"categoryNames":"分类名称",
	"newsType":1,
     "status":2,
     "gmtPublish":1603108140390
},
{
	"title": "test",
	"publisher": "dsd",
	"digest": "sfdss",
	"fileContent": [{
		"url": "http://ww.baidu.com"
	}],
	"coverImg": "http://baas.uban360.net:21006/sfs/file?digest=fid431e3a147c4291aeae5e19ad82a2994e",
	"categoryId": 184337,
	"baasNewsType": 2,
	"categoryNames":"分类名称",
	"newsType":1,
     "status":2,
     "gmtPublish":1603108140390
}]

....

`body数据字段说明` +

|===
|名称 |类型 |必须 |默认值 |说明

| title
| String
| 是
|
| 新闻标题

| digest
| string
| 否
|
| 新闻摘要

| coverImg
| string
| 是
|
| 新闻封面图

| publisher
| string
| 是
|
| 作者

| categoryId
| Long
| 是
|
| 分类Id

| categoryNames
| string
| 是
|
| 分类名称

| gmtPublish
| Long
| 是
|
| 发布时间 (时间戳 ms)

| newsType
| Integer
| 是
|
| 类型 0 新闻 1 公告

| baasNewsType
| Integer
| 是
|
| 公告都传0  新闻：2-普通新闻 3-视频新闻

| fileContent
| 对象格式（[{}]）
| 是
|
|链接新闻的url

| status
| Integer
| 是
| 2
| 状态 -1-删除 0-失效 2-正常


|===

Response响应说明： +
`成功响应数据格式:`

[source,json]
....
{
"status": 0, //状态码0表示成功, 其他表示失败
"success": true //true表示成功, false表示失败
}
....

`失败响应数据格式:`

[source,json]
....
{
"status":500, //状态码0表示成功, 其他表示失败
"success":false, //true表示成功, false表示失败
"message":"消息格式错误" //错误提示消息
}
....
=== 新闻、公告 分类推送
接口地址：/newsCategory/push +
请求方式：POST +
接口描述：新闻、公告分类推送 +
Request请求说明： +

`Body数据格式:` +

[source,json]
....
[{  "id":45678,
	"categoryName": "分类名称",
	"parentId":12,
	"categoryType":1,
    "status":0
},
{
	"id":45678,
	"categoryName": "分类名称",
	"parentId":12,
	"categoryType":1,
    "status":0
}]
....
`body数据字段说明` +

|===
|名称 |类型 |必须 |默认值 |说明

| id
| Long
| 是
|
| 分类Id

| categoryName
| string
| 是
|
| 分类名称

| parentId
| Long
| 是
| 0
| 父分类Id

| categoryType
| Integer
| 是
|
| 新闻分类 0-新闻，1-公告

| status
| Integer
| 是
| 0
| 0-正常，-1-删除
|===

Response响应说明： +
`成功响应数据格式:`
[source,json]
....
{
    "code": 200, //code=200表示接口调用成功,其他标识失败
    "success": true //true表示成功, false表示失败
    "data": Object //返回数据
}
....
`失败响应数据格式:`
[source,json]
....
{
    "code":500, //code=200表示接口调用成功,其他标识失败
    "success":false, //true表示成功, false表示失败
    "msg":"接口失败原因" //错误提示消息
}
....