== 新闻、公告

=== 新闻、公告拉取

接口名称：接收新闻、公告信息 +
接口地址：/news/pull +
请求方式：POST（content-type:application/json; charset=utf-8） +
Request请求说明： +

`Body数据格式:` +

[source,json]
....
[{
	"id": 12,
	"title": "test",
	"publisher": "dsd",
	"digest": "sfdss",
	"fileContent": [{
		"url": "http://ww.baidu.com"
	}],
	"coverImg": "http://baas.uban360.net:21006/sfs/file?digest=fid431e3a147c4291aeae5e19ad82a2994e",
	"categoryId": 184337,
	"baasNewsType": 2,
	"categoryNames":"分类名称",
	"newsType":1,
     "status":1,
     "gmtPublish":232131231
},
{
	"id": 12,
	"title": "test",
	"publisher": "dsd",
	"digest": "sfdss",
	"fileContent": [{
		"url": "http://ww.baidu.com"
	}],
	"coverImg": "http://baas.uban360.net:21006/sfs/file?digest=fid431e3a147c4291aeae5e19ad82a2994e",
	"categoryId": 184337,
	"baasNewsType": 2,
	"categoryNames":"分类名称",
	"newsType":1,
     "status":1,
     "gmtPublish":2123182132
}]

....

`body数据字段说明` +

|===
|名称 |类型 |必须 |默认值 |说明

| id
| Long
| 是
| 0
| 新闻Id

| title
| String
| 是
|
| 新闻标题

| digest
| string
| 否
|
| 新闻摘要

| coverImg
| string
| 是
|
| 新闻封面图

| publisher
| string
| 是
|
| 作者

| categoryId
| Long
| 是
|
| 分类Id

| categoryNames
| string
| 是
|
| 分类名称

| gmtPublish
|
| 是
|
| 时间戳

| newsType
| Integer
| 是
|
| 类型 0 新闻 1 公告

| baasNewsType
| Integer
| 是
|
| 仅对新闻 0 普通新闻 1 文件新闻 2 链接新闻 3 视屏新闻

| fileContent
|
| 是
|
|链接新闻的url

| status
| Integer
| 是
|
| 状态 2正常


|===

Response响应说明： +
`成功响应数据格式:`

[source,json]
....
{
"status": 0, //状态码0表示成功, 其他表示失败
"success": true //true表示成功, false表示失败
}
....

`失败响应数据格式:`

[source,json]
....
{
"status":4800, //状态码0表示成功, 其他表示失败
"success":false, //true表示成功, false表示失败
"message":"消息格式错误" //错误提示消息
}
....

`status状态码说明:`

|===
|状态码 |说明

| 0
| 成功

| 4800
| 消息格式错误

| 4801
| 消息类型不能为空

| 4802
| 消息标题不能为空

|4803
|消息接收者列表不能为空

|4804
|加密消息的密钥ID不能为空

|4805
|接收者不属于当前操作的企业

|4806
|消息发送失败

|===